spring:
  application:
    name: flywaydatabasemanager
  datasource:
    username: root
    url: jdbc:mysql://mysqldb:3306/customerportallibrary
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
 
server:
  port: 8082
