spring:
  application:
    name: flywaydatabasemanager
  datasource:
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_URL}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
