spring:
  application:
    name: flyway-database-manager
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
